
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE APARENT ARCH CIERRA COMA CPARENT CREA DIRECCION INGRESA INICIA LISTA MUESTRA NOMBRE NUMERO OCUPACION TERMINAA : INICIAA : TERMINAA : CREA APARENT ARCH CPARENTA : ABRE APARENT ARCH CPARENTA : INGRESA APARENT NUMERO COMA NOMBRE COMA NUMERO COMA OCUPACION COMA DIRECCION CPARENTA : LISTAA : MUESTRA APARENT NUMERO CPARENTA : CIERRA'
    
_lr_action_items = {'INICIA':([0,],[2,]),'TERMINA':([0,],[3,]),'CREA':([0,],[4,]),'ABRE':([0,],[5,]),'INGRESA':([0,],[6,]),'LISTA':([0,],[7,]),'MUESTRA':([0,],[8,]),'CIERRA':([0,],[9,]),'$end':([1,2,3,7,9,18,19,21,29,],[0,-1,-2,-6,-8,-3,-4,-7,-5,]),'APARENT':([4,5,6,8,],[10,11,12,13,]),'ARCH':([10,11,],[14,15,]),'NUMERO':([12,13,23,],[16,17,24,]),'CPARENT':([14,15,17,28,],[18,19,21,29,]),'COMA':([16,22,24,26,],[20,23,25,27,]),'NOMBRE':([20,],[22,]),'OCUPACION':([25,],[26,]),'DIRECCION':([27,],[28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'A':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> A","S'",1,None,None,None),
  ('A -> INICIA','A',1,'p_inicia','AnalizadorSintactico2.py',8),
  ('A -> TERMINA','A',1,'p_termina','AnalizadorSintactico2.py',12),
  ('A -> CREA APARENT ARCH CPARENT','A',4,'p_crea','AnalizadorSintactico2.py',17),
  ('A -> ABRE APARENT ARCH CPARENT','A',4,'p_abre','AnalizadorSintactico2.py',22),
  ('A -> INGRESA APARENT NUMERO COMA NOMBRE COMA NUMERO COMA OCUPACION COMA DIRECCION CPARENT','A',12,'p_ingresa','AnalizadorSintactico2.py',27),
  ('A -> LISTA','A',1,'p_lista','AnalizadorSintactico2.py',32),
  ('A -> MUESTRA APARENT NUMERO CPARENT','A',4,'p_muestra','AnalizadorSintactico2.py',38),
  ('A -> CIERRA','A',1,'p_cierra','AnalizadorSintactico2.py',45),
]
